config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products, only: [:index, :import] do
    collection do
      get :index
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  QUOTE_CHAR = '^'.freeze    
  COLUMNS = "price_list, brand, code, stock, cost, name, created_at, updated_at".freeze
  CODE_CONVERTER = {
    'utf-8' => "UTF-8",
    'UTF-8' => "UTF-8",
    'windows-1251' => 'CP1251:utf-8'
  }.freeze
  COLUMN_PARSER = {
    'Производитель' => "brand",
    'Бренд' => "brand",
    'Артикул' => 'code',
    "﻿\"Артикул\"" => 'code',
    'Номер' => 'code',
    'Кол-во' => "stock",
    'Количество' => "stock",
    'Цена' => "cost",
    'Наименование' => "name",
    'НаименованиеТовара' => "name",
  }.freeze

	def self.import(file)
    mem_usage_before = print_memory if Rails.env.development?
    time = Benchmark.realtime do
      price_list = file.original_filename.to_s
      ActiveRecord::Base.transaction do
        # https://postgrespro.ru/docs/enterprise/12/sql-copy
        products_command =
          "copy products (#{COLUMNS}) from stdin with csv delimiter ';' quote '#{QUOTE_CHAR}'"

        Product.where(price_list: price_list).delete_all
        ActiveRecord::Base.connection.reset_pk_sequence!('products')

        strVar = File.open(file.path, &:readline)
        col_del = strVar.index(';').nil? ? ',' : ';'
        char_detect = CharDet.detect(strVar)

        raw_connection.copy_data products_command do
          # https://ruby-doc.org/stdlib-2.7.2/libdoc/csv/rdoc/CSV.html
          CSV.foreach(file.path, 
                      headers: :first_row, 
                      liberal_parsing: true, 
                      encoding: CODE_CONVERTER[char_detect['encoding']], 
                      col_sep: col_del
                     ) do |row|
            begin
              import_action(row.to_hash, price_list)
            rescue 
              # ignore record
            end
          end
        end 
      end 
    end 
    if Rails.env.development?
      mem_usage_after = print_memory
      mem_usage = mem_usage_after - mem_usage_before
      puts "Memory usage: #{mem_usage} KB"
      puts "Finish in: #{time.round(2)}"
    end
  end	

  def created_at_time()
    # https://devdocs.io/ruby~3/datetime#method-i-strftime
    created_at.strftime("%T")  
  end

  private
  def self.raw_connection
    @raw_connection ||= ActiveRecord::Base.connection.raw_connection
  end

  def self.import_action(input_hash, file_name)
    # парсим данные
    hsh = input_hash.transform_keys {|k| COLUMN_PARSER[k] }
    # только для разрешённых записей
    if !hsh['brand'].empty? && !hsh['code'].empty? 
      # дополнительные условия
      hsh['stock'] = hsh['stock'].index('>').nil? ? 
        hsh['stock'] : hsh['stock'].gsub('>', '')
      hsh['cost'] = input_hash['Цена'].tr(',', '.')
      # недостающие данные
      time = Time.now.localtime.strftime("%Y-%m-%d %H:%M:%S")
      # стримим подготовленный чанк данных в postgres 
      s = "#{file_name};#{hsh['brand']};#{hsh['code']};#{hsh['stock']};#{hsh['cost']};#{hsh['name']};#{time};#{time}\n"
      raw_connection.put_copy_data(s)
    end 
  end

  def self.memory
    `ps -o rss= -p #{Process.pid}`.to_i
  end

  def self.print_memory
    m = memory
    puts "Memory: #{m} KB"
    m
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def import
    begin
      Product.import(params[:file])
      redirect_to products_path, notice: "Products added successfully"
    rescue CSV::MalformedCSVError => e
      redirect_to products_path, notice: "Error in the input data structure: #{e.message}"
    rescue Exception => e
      redirect_to products_path, notice: "Something went wrong: #{e.message}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_s
      when "notice" then "toast toast-primary"
      when "alert" then "toast toast-warning"
      else "toast toast-#{level}"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    meta http-equiv="Content-Type" content="text/html; charset=utf-8"
    title BackendImport
    = csrf_meta_tags
    = csp_meta_tag
    
    = stylesheet_link_tag  "application", 'data-turbolinks-track': 'reload', media: 'all'
    = javascript_pack_tag  "application", 'data-turbolinks-track': 'reload'

  body
    main class="container"
      - flash.each do |level, text|
        div class="#{flash_class(level)}"
          p = text 

      = yield

app/views/products/_lst_product.slim
tr 
  td = lst_product.id
  td = lst_product.created_at_time
  td = lst_product.price_list
  td = lst_product.brand
  td = lst_product.code
  td = lst_product.stock
  td = lst_product.cost
  td = lst_product.name

app/views/products/index.slim
h1 Import of products from CSV-file
= form_with url: import_products_path, multipart: true, remote: true do |form|
  = form.label  :file, 'File' 
  = form.file_field :file 
  = form.submit 'Upload'

table class="table table-striped"
  thead
    th class="text-center text-tiny" 
      h3 id
    th class="text-center text-tiny" 
      h3 created_at
    th class="text-center text-tiny" 
      h3 price_list
    th class="text-center text-tiny" 
      h3 brand
    th class="text-center text-tiny" 
      h3 code
    th class="text-center text-tiny" 
      h3 stock
    th class="text-center text-tiny" 
      h3 cost
    th class="text-center text-tiny" 
      h3 name

  tbody
    = render partial: "lst_product", collection: @products